[package]
name = "rust_raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_pcg = "0.3.1"

[profile.release]
debug=true
panic="abort"
